// podTemplate(yaml: readTrusted('yaml/pod.yaml')) {
//   node(POD_LABEL) {   
//     stage('Run shell') {
//         sh "echo hello world"
//         sh "pwd && ls -l ./"
//         script {
//             build_tag = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
//             }
//           }
//     stage('Build Docker image') {
//       container('busybox') {
//         sh "echo hello from $POD_CONTAINER"
//         sh "pwd && ls -l ./"
//         echo "${build_tag}"
//       }
//     }
//   }
// }
// 声明式Pipeline
pipeline {
  agent {
    kubernetes {
      cloud 'kubernetes'
      slaveConnectTimeout 1200
      //inheritFrom 'mypod' // 指定pod 模板, 如果不指定可以通过yamlfile指定文件
      workspaceVolume hostPathWorkspaceVolume(hostPath: "/home/jenkins/agent", readOnly: false)   //持久化
      yamlFile 'yaml/pod.yaml'
    }
  }
  environment { 
        CC = 'clang'
    }
  parameters {
    gitParameter branchFilter: 'origin/(.*)', defaultValue: 'master', name: 'Name', type: 'PT_BRANCH'
  }
  stages {
    stage('Prepare') {
      steps {
        echo "${CC}"
        echo "${Name}"
        echo "${params.Name}"
        echo "${BUILD_TAG}"
      }
    }
    stage("Pulling Code by trigger"){
      steps{
          sh '''
          pwd && id
          '''
          script {
              COMMIT_ID = sh(
                returnStdout: true,
                script: "git log -n 1 --pretty=format:'%h'"
              ).trim()
              TAG = BUILD_TAG + '-' + COMMIT_ID
              println "Current branch is ${Name}, Commit ID is ${COMMIT_ID}"
            }
      }
      

    }

  }
    
}