apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nerdctl-client
    image: nerdctl:v1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/usr/local/share/ca-certificates"
      name: "ca"
      readOnly: false
    - mountPath: "/run/containerd/containerd.sock"
      name: "containerd"
      readOnly: false
    - mountPath: "/run/buildkit/buildkitd.sock"
      name: "buildkitd"
      readOnly: false
  - name: "inbound-agent"
    image: "jenkins/inbound-agent:jdk11"
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
  hostAliases:
  - hostnames:
    - "myregistry.io"
    ip: "10.4.55.209"
  nodeSelector:
    kubernetes.io/hostname: "utility1"
  tolerations:
  - effect: "NoSchedule"
    operator: "Exists"
  volumes:
  - hostPath:
      path: "/run/containerd/containerd.sock"
    name: "containerd"
  - name: "ca"
    secret:
      optional: false
      secretName: "docker-ca"
  - hostPath:
      path: "/run/buildkit/buildkitd.sock"
    name: "buildkitd"